version: '3'

services:
  backend:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - MONGO_DATABASE=crud-task
      - NODE_ENV=development
      - REDIS_HOST=redis
      - TOKEN_EXPIRY=1d

    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0.2-focal
    restart: always

  redis:
    image: redis:alpine3.16
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

